const RESTAURANTS = [
  {
    id: 1,
    name: "온기식당",
    category: "한식",
    area: "서울 종로",
    tag: "정갈한 한상",
    description: "제철 재료로 매일 다르게 차리는 가정식 한상.",
    img: "assets/images/restaurants/01.jpg",
    reviews: [
      { author: "j_eats", rating: 5, text: "밑반찬 하나하나 정성이 느껴져요. 재방문 의사 100%." },
      { author: "seoul_walker", rating: 4, text: "혼밥하기도 좋고 조용해서 좋았어요." },
      { author: "jongno_diner", rating: 5, text: "국물 요리가 특히 자극적이지 않고 편안해요." },
    ],
  },
  {
    id: 2,
    name: "브릭버거",
    category: "양식",
    area: "서울 이태원",
    tag: "육즙 가득 수제버거",
    description: "직접 반죽한 번과 두꺼운 패티로 승부하는 수제버거집.",
    img: "assets/images/restaurants/02.jpg",
    reviews: [
      { author: "burger_hoon", rating: 5, text: "패티 육즙이 미쳤습니다. 웨이팅 감수할 맛." },
      { author: "minji.k", rating: 4, text: "번이 촉촉해서 끝까지 물리지 않고 먹었어요." },
      { author: "itaewon_foodie", rating: 5, text: "소스 조합이 특히 독특하고 중독적이에요." },
    ],
  },
  {
    id: 3,
    name: "조용한 서재",
    category: "카페",
    area: "서울 성수",
    tag: "책 냄새 나는 카페",
    description: "오래된 책과 원두 향이 함께 머무는 조용한 동네 카페.",
    img: "assets/images/restaurants/03.jpg",
    reviews: [
      { author: "bookworm_yj", rating: 5, text: "혼자 책 읽기 딱 좋은 조도와 좌석." },
      { author: "coffee_daily", rating: 5, text: "핸드드립 원두가 매주 바뀌어서 재밌어요." },
      { author: "quiet_reader", rating: 4, text: "좌석 간격이 넓어서 노트북 작업하기도 좋아요." },
    ],
  },
  {
    id: 4,
    name: "스시 나루",
    category: "일식",
    area: "서울 청담",
    tag: "제철 오마카세",
    description: "매일 새벽 공수한 제철 생선으로 채우는 오마카세 코스.",
    img: "assets/images/restaurants/04.jpg",
    reviews: [
      { author: "sushi_lover", rating: 5, text: "제철 재료 설명을 들으며 먹으니 더 맛있었어요." },
      { author: "hyun_", rating: 4, text: "가격대는 있지만 그만한 값을 합니다." },
      { author: "omakase_diary", rating: 5, text: "셰프님이 재료마다 스토리를 들려주셔서 더 특별했어요." },
    ],
  },
  {
    id: 5,
    name: "달콤제과",
    category: "베이커리",
    area: "서울 연남",
    tag: "매일 굽는 크루아상",
    description: "국내산 밀가루와 발효버터만 고집하는 동네 베이커리.",
    img: "assets/images/restaurants/05.jpg",
    reviews: [
      { author: "bread_addict", rating: 5, text: "오픈런 안 하면 오후엔 품절이에요. 그만큼 맛있음." },
      { author: "yeonnam_local", rating: 5, text: "결 살아있는 크루아상은 여기가 최고." },
      { author: "pastry_hunter", rating: 4, text: "단맛이 과하지 않아서 매일 먹어도 질리지 않아요." },
    ],
  },
  {
    id: 6,
    name: "스트리트버거",
    category: "양식",
    area: "서울 홍대",
    tag: "바삭한 감자튀김과 함께",
    description: "빠르게, 하지만 재료는 타협 없이 준비하는 캐주얼 버거.",
    img: "assets/images/restaurants/06.jpg",
    reviews: [
      { author: "hongdae_night", rating: 4, text: "친구들이랑 가볍게 먹기 좋아요." },
      { author: "fries_fan", rating: 5, text: "감튀가 눅눅하지 않고 끝까지 바삭해요." },
      { author: "late_night_snack", rating: 4, text: "포장해도 눅눅해지지 않는 포장 상태가 인상적이었어요." },
    ],
  },
  {
    id: 7,
    name: "나폴리 피자집",
    category: "양식",
    area: "서울 이태원",
    tag: "화덕에 구운 도우",
    description: "장작 화덕에서 90초 만에 구워내는 정통 나폴리 피자.",
    img: "assets/images/restaurants/07.jpg",
    reviews: [
      { author: "pizza_traveler", rating: 5, text: "도우 끝부분이 폭신하면서 살짝 탄 향이 좋아요." },
      { author: "j_eats", rating: 4, text: "치즈 비율이 딱 좋습니다." },
      { author: "napoli_style", rating: 5, text: "현지에서 먹던 그 맛 그대로예요." },
    ],
  },
  {
    id: 8,
    name: "브런치룸",
    category: "카페",
    area: "서울 한남",
    tag: "여유로운 주말 브런치",
    description: "햇살 좋은 창가 자리에서 즐기는 여유로운 브런치 코스.",
    img: "assets/images/restaurants/08.jpg",
    reviews: [
      { author: "weekend_brunch", rating: 5, text: "에그베네딕트 소스가 일품이에요." },
      { author: "hannam_resident", rating: 4, text: "테이블 간격이 넓어서 편하게 대화하기 좋아요." },
      { author: "sunday_brunch", rating: 5, text: "플레이팅도 예쁘고 사진 찍기 좋아요." },
    ],
  },
  {
    id: 9,
    name: "산책식당",
    category: "한식",
    area: "서울 마포",
    tag: "집밥 같은 한 끼",
    description: "동네 주민들이 매일 찾는, 정직한 재료의 집밥식당.",
    img: "assets/images/restaurants/09.jpg",
    reviews: [
      { author: "mapo_dweller", rating: 5, text: "타지에서 그리웠던 집밥 맛이에요." },
      { author: "seoul_walker", rating: 5, text: "국물 요리가 특히 훌륭합니다." },
      { author: "local_regular", rating: 4, text: "가격 대비 반찬 구성이 알차요." },
    ],
  },
];

const CATEGORIES = ["전체", "한식", "카페", "일식", "양식", "베이커리"];
